import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import dotenv from "dotenv";

dotenv.config();
const baseUrl = 'http://localhost:3000'
const Helper = {
  hashPassword(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8));
  },
  comparePassword(hashPassword, password) {
    return bcrypt.compareSync(password, hashPassword);
  },
  generateToken(id, email) {
    const token = jwt.sign(
      {
        id,
        email
      },
      process.env.SECRET,
      { expiresIn: "7d" }
    );
    return token;
  },
  emailSender(details) {
    const DOMAIN = "mg.bus-connect.me";
    const mailgun = require("mailgun-js")({
      apiKey: process.env.MAILGUN_API_KEY,
      domain: DOMAIN,
    });

    const data = {
      from: "admin@mg.bus-connect.me",
      to: details.email,
      subject: details.subject,
      html: details.html,
      "o:tracking": "False",
    };

    return mailgun.messages().send(data, (error, body) => {
      if (error) {
        console.log(error);
      }
    });
  },

  async generateInvitationEmail(senderEmail, recipientEmail, clubName, clubID) {
    const details = {
      email: recipientEmail,
      subject: "Club Invitation",
      html: `'<div style="width: 90%; margin: 5em auto;
       box-shadow: 0 0 10px rgba(0,0,0,.9);">
        <div>
          <div>
            <div style="background-color: #00bfa6; height: 3rem; width: 100%">
                <h2 style="text-align: center; color: white;
                 padding-top: 10px;">Club Manager</h2>
            </div>
            <h4 style="text-align: center">Hi! ${recipientEmail}</h4>
          </div>
          <div style=" padding: 0px 20px 20px 20px">
            <div>
              <p>${senderEmail} sent you an invitation to join a club Please Click here <button style="color: white; background-color: #00bfa6;
              border: none; border-radius: 10px; text-align: center;
               padding: 10px;">
 
               <a  href="${process.env.baseUrl}/clubs/member?club_name=${clubName}&club_id=${clubID}?email=${recipientEmail}"
                style="text-decoration: none;
                color: white;">Join Club</a></button> to Join the club</p>
            </div>
            <div>
              <h3 style="text-align: center">Thank you</h3>
              <h3 style="text-align: center">
              Please do not reply, this is an autogenerated email.</h3>
            </div>
          </div>
        </div>
      </div>`,
    };
    try {
      const isEmailSent = await Helper.emailSender(details);
      if (isEmailSent) {
        return true;
      }
    } catch (error) {
      return false;
    }
    // return Helper.emailSender(details);
  },

  isValidNumber(number) {
    return /^\d+$/.test(number);
  },
};

export default Helper;